### PR TITLE
Fix images not loading in related monuments

### PR DESCRIPTION
**Pull request by benvogler**
Do not merge until I get a chance to test this tonight. Can't test right now because I haven't gotten PostGIS working on macos yet.

### CODE REVIEW

**Comment by benvogler** [comment]
@njd9419 this is ready to go and working locally. Unfortunately I had to change it so that it loads the image collection individually for each monument which is way less efficient but we can revisit that at another time

**Comment by njd9419** [comment]
I added a commit so that the Travis build would kick off again.

**Comment by njd9419** [comment]
For some reason Travis isn't saying that the build completed even though it has.

**Comment by benvogler** [comment]
I turned off the travis requirement for now. Hopefully just a blip on this PR...

**Pull request merged**
