### PR TITLE
couple small bug fixes

### PR DESCRIPTION
**Pull request by renchauret**
fix for temp monuments showing as permanent in edit page
fix for broken back button on monument page

### CODE REVIEW

**Review by dwang305 — COMMENTED** [review]
For the back button bug, it is fixed if you selected a monument from the map or used the "View Public Page" button from the manage monuments page. However, the bug still exists if you navigate to the monument page using the Nearby Monuments sidebar, Related Monuments sidebar, Map, or being auto redirected to the monument's page after submitting an edit.

**Comment by renchauret** [comment]
> For the back button bug, it is fixed if you selected a monument from the map or used the "View Public Page" button from the manage monuments page. However, the bug still exists if you navigate to the monument page using the Nearby Monuments sidebar, Related Monuments sidebar, Map, or being auto redirected to the monument's page after submitting an edit.

I cannot recreate the issue in Map.  I am seeing it in nearby and related, and it's being a real pain to fix, so I will leave this PR open for now

**Comment by renchauret** [comment]
This one is being really finnicky. Nearby and related should now work after clicking the back button twice. I think that is good enough for now. I will create a bug ticket to improve this later

**Review by dwang305 — CHANGES_REQUESTED** [review]
Suggested and Nearby work as described and I can no longer recreate the Map bug so that's fine.   But a major issue cropped up. If you click a monument from the "Manage Monuments" search, the page is empty.

**Review by dwang305 — APPROVED** [review]

**Pull request merged**
